version: '2'
services:
  api:
    build: api/.
    command: 'yarn run start-dev'
    depends_on:
      - db
      - redis
    env_file:
      - api/.env
    ports:
      - '8080:8080'
      - '9229:9229'
    expose:
      - 9229
    volumes:
      - './api/.:/opt/app'
      - /opt/app/node_modules
    image: 'ocblog_api:latest'
  frontend:
    build: frontend/.
    command: 'npm start'
    ports:
      - '0.0.0.0:3000:3000'
      - '0.0.0.0:3001:3001'
      - '0.0.0.0:3002:3002'
    volumes:
      - './frontend/.:/opt/app'
      - /opt/app/node_modules
    image: 'ocblog_frontend:latest'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: b5EGm7PxcKcuD4Vj8N5bN
      POSTGRES_DB: o_c_blog_local
      POSTGRES_USER: o_c_blog
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
  redis:
    build: docker/definitions/redis
    image: 'ocblog_redis:latest'
